// =============================================================================
// miserly — code generator
// =============================================================================
//
// Reads the canonical feature catalog (features.config.mjs) + what is actually
// installed in node_modules, then writes two generated TypeScript files plus
// the materialized integration adapters.
//
// Why generate code instead of just reading env vars at runtime?
//   A browser bundle must be able to BUILD even when an optional package is not
//   installed. Vite/Rollup resolve every import at build time, so a stray
//   `import "gpt-tokenizer"` would break the build when that 55 MB package is
//   absent. The fix: the importing code only exists on disk (`*.ts`) when the
//   package is installed. When it is not, we leave only an inert `*.ts.tmpl`
//   template, which the TypeScript compiler and Vite both ignore.
//
// Outputs (all git-ignored, regenerated on demand):
//   • src/features.generated.ts          — availability + env defaults + metadata
//   • src/integrations/generated.ts       — wires the active adapters
//   • src/integrations/<adapter>.ts        — materialized from .ts.tmpl when installed
//
// Run via: `node scripts/generate.mjs` (also runs automatically on postinstall,
// predev, prebuild and pretypecheck — see package.json).
// -----------------------------------------------------------------------------
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { FEATURES, getFeature } from "./features.config.mjs";
import { ensureDir, featurePackagesInstalled, paths } from "./lib.mjs";

const BANNER = `// ============================================================================
// AUTO-GENERATED by scripts/generate.mjs — DO NOT EDIT BY HAND.
// Re-run \`node scripts/generate.mjs\` (or \`npm run setup\`) to update.
// ============================================================================
`;

/**
 * Integration wiring. Each entry maps a feature to the adapter file that gets
 * materialized when its package is installed, and the export lines that
 * `src/integrations/generated.ts` should contain for the installed / missing
 * states.
 */
const INTEGRATIONS = [
  {
    featureKey: "accurateTokenizer",
    template: "tokenizer/accurate.ts.tmpl",
    output: "tokenizer/accurate.ts",
    installed: `import { countAccurate as _countAccurate } from "./tokenizer/accurate";
export const countAccurate: ((text: string) => number) | null = _countAccurate;`,
    missing: `export const countAccurate: ((text: string) => number) | null = null;`,
  },
  {
    featureKey: "documentParsing",
    template: "docparse/real.ts.tmpl",
    output: "docparse/real.ts",
    installed: `import { parseBinaryDocument as _parseBinaryDocument } from "./docparse/real";
export const parseBinaryDocument: ((file: File) => Promise<string>) | null = _parseBinaryDocument;`,
    missing: `export const parseBinaryDocument: ((file: File) => Promise<string>) | null = null;`,
  },
];

function materializeAdapter(integration, installed) {
  const outPath = join(paths.integrations, integration.output);
  const tmplPath = join(paths.integrations, integration.template);

  if (installed) {
    if (!existsSync(tmplPath)) {
      throw new Error(`Missing adapter template: ${tmplPath}`);
    }
    const body = readFileSync(tmplPath, "utf8");
    writeFileSync(outPath, BANNER + body, "utf8");
  } else if (existsSync(outPath)) {
    // Remove the materialized adapter so the compiler never sees the import.
    rmSync(outPath);
  }
}

function buildIntegrationsGenerated(availability) {
  const blocks = INTEGRATIONS.map((it) =>
    availability[it.featureKey] ? it.installed : it.missing,
  );
  return `${BANNER}
// Active integration adapters. When a package is not installed the export is
// \`null\` and the app falls back to its built-in behavior.

${blocks.join("\n\n")}
`;
}

function tsString(value) {
  return JSON.stringify(value);
}

function buildFeaturesGenerated(availability) {
  const metaEntries = FEATURES.map((f) => {
    const packages = `[${f.packages.map(tsString).join(", ")}]`;
    return `  {
    key: ${tsString(f.key)},
    envVar: ${tsString(f.envVar)},
    label: ${tsString(f.label)},
    description: ${tsString(f.description)},
    heavy: ${f.heavy},
    packages: ${packages},
    sizeLabel: ${f.sizeLabel === null ? "null" : tsString(f.sizeLabel)},
    default: ${f.default},
    runtimeToggle: ${f.runtimeToggle},
  }`;
  }).join(",\n");

  const availabilityEntries = FEATURES.map(
    (f) => `  ${f.key}: ${availability[f.key] === true},`,
  ).join("\n");

  const envDefaultEntries = FEATURES.map(
    (f) =>
      `  ${f.key}: parseFlag(import.meta.env.${f.envVar}, ${f.default}),`,
  ).join("\n");

  return `${BANNER}
import { parseFlag } from "@/config/flags";

export interface FeatureMeta {
  key: FeatureKey;
  envVar: string;
  label: string;
  description: string;
  heavy: boolean;
  packages: string[];
  sizeLabel: string | null;
  default: boolean;
  runtimeToggle: boolean;
}

/** Whether each feature's npm package(s) are installed (decided at build time). */
export const FEATURE_AVAILABILITY = {
${availabilityEntries}
} as const;

export type FeatureKey = keyof typeof FEATURE_AVAILABILITY;

/** Build-time default enabled-state, read from \`.env\` (VITE_FEATURE_*). */
export const FEATURE_ENV_DEFAULT: Record<FeatureKey, boolean> = {
${envDefaultEntries}
};

/** Catalog metadata for the Settings UI. */
export const FEATURE_META: FeatureMeta[] = [
${metaEntries},
];
`;
}

export function generate({ log = () => {} } = {}) {
  ensureDir(paths.integrations);

  /** @type {Record<string, boolean>} */
  const availability = {};
  for (const f of FEATURES) {
    availability[f.key] = featurePackagesInstalled(f);
  }

  for (const it of INTEGRATIONS) {
    const feature = getFeature(it.featureKey);
    const installed = availability[it.featureKey] === true;
    materializeAdapter(it, installed);
    log(
      `  ${installed ? "✓" : "·"} ${feature?.label ?? it.featureKey}: ${
        installed ? "installed" : "not installed (using fallback)"
      }`,
    );
  }

  writeFileSync(
    join(paths.src, "integrations", "generated.ts"),
    buildIntegrationsGenerated(availability),
    "utf8",
  );
  writeFileSync(
    join(paths.src, "features.generated.ts"),
    buildFeaturesGenerated(availability),
    "utf8",
  );

  return availability;
}

// Run directly: `node scripts/generate.mjs`
if (import.meta.url === `file://${process.argv[1]}`) {
  const availability = generate({ log: (m) => console.log(m) });
  const on = Object.entries(availability)
    .filter(([, v]) => v)
    .map(([k]) => k);
  console.log(`\nmiserly: generated feature glue. Available: ${on.join(", ")}`);
}
