// Public, stable entry point for feature metadata + availability.
// The actual values live in the generated file (regenerated by the installer).
import {
  FEATURE_AVAILABILITY,
  FEATURE_ENV_DEFAULT,
  FEATURE_META,
  type FeatureKey,
  type FeatureMeta,
} from "./features.generated";

export { FEATURE_AVAILABILITY, FEATURE_ENV_DEFAULT, FEATURE_META };
export type { FeatureKey, FeatureMeta };

/** All feature keys, in catalog order. */
export const FEATURE_KEYS = FEATURE_META.map((m) => m.key);

/** Metadata for a single feature (every key is guaranteed to exist). */
export function featureMeta(key: FeatureKey): FeatureMeta {
  const meta = FEATURE_META.find((m) => m.key === key);
  if (!meta) throw new Error(`Unknown feature: ${key}`);
  return meta;
}

/** Whether a feature's package(s) are installed (fixed at build time). */
export function isFeatureAvailable(key: FeatureKey): boolean {
  return FEATURE_AVAILABILITY[key];
}
